packages:
  - 'packages/*'

catalog:
  '@babel/parser': ^7.26.2
  '@babel/types': ^7.26.0
  'vite': ^6.0.1
  'magic-string-ast': ^0.6.2
  'source-map-js': 1.2.0
  'svelte': 4.2.18
  'tsdown': ^0.4.4
  'unbuild': ^2.0.0
  '@shikijs/monaco': ^1.24.0
  'monaco-editor': ^0.52.0
  'shiki': ^1.24.0
