name: Label sync

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/github-label-sync.yml
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/github-label-sync-action@v0
